#!/bin/bash
# This file contains information oabout tour team.
# and our project.

#C18 students LAVAL(FRANCE) 2022-2023.

José Fermandez Armas: <4990@holbertonstudents.com>

Sébastien Jonad: <5151@holbertonstudents.com>
